name: Build Windows

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Rebuild native modules for Windows
      run: npm rebuild better-sqlite3 --build-from-source

    - name: Build Electron app for Windows
      run: npm run build:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-installers
        path: |
          release/*.exe
          release/*.exe.blockmap
        retention-days: 7

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*.exe
          release/*.exe.blockmap
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
